# config/config.yaml
Telegram:
  Token: ${TELEGRAM_TOKEN}

DB:
  Host: ${DB_HOST}
  Port: ${DB_PORT}
  User: ${DB_USER}
  Password: ${DB_PASSWORD}
  DBName: ${DB_NAME}
  SSLMode: ${DB_SSL_MODE}
  MaxOpenConns: 20
  MaxIdleConns: 10
  ConnLifetime: 300s

Stripe:
  SecretKey: ${STRIPE_SECRET_KEY}
  PublicKey: ${STRIPE_PUBLIC_KEY}
  WebhookKey: ${STRIPE_WEBHOOK_KEY}
  ProductID: ${STRIPE_PRODUCT_ID}
  PriceID: ${STRIPE_PRICE_ID}

GPT:
  APIKey: ${GPT_API_KEY}
  Model: ${GPT_MODEL}

Server:
  Port: ${SERVER_PORT}

ShutdownTimeout: 10s